// ─────────────────────────────────────────────────────────────────────────────
// test_golden_render.cpp — golden-render regression fingerprints (docs/35 §B3)
//
// The refit pipeline re-fits whatever the engine currently does, so it can
// never DETECT an unintended sonic change — it absorbs it.  This gate is the
// complementary instrument: fixed-seed renders of every chain preset at two
// drive points are reduced to spectral fingerprints (RMS + H1..H5) and
// compared against a checked-in reference within ±0.5 dB.
//
// When a physics change is INTENDED to move the sound, regenerate the
// reference and commit it with the change (the diff of the reference file
// then documents exactly what moved):
//
//   ./tests/valvra_tests "[golden-regen]" > /tmp/golden.h   (from build dir)
//   → paste the emitted table into tests/golden_render_reference.h
//
// Components sitting below −80 dBFS in the reference are skipped (noise-
// floor-dominated bins are not stable enough to gate at ±0.5 dB).
// ─────────────────────────────────────────────────────────────────────────────
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "TubeAmpChain.h"
#include "golden_render_reference.h"

#include <cmath>
#include <cstdio>
#include <numbers>
#include <vector>

using namespace valvra::dsp;

namespace {

constexpr double kGoldenSampleRate = 48000.0;
constexpr double kGoldenFreq = 220.0;
constexpr double kGoldenAmps[2] = { 0.1, 0.7 };

struct Fingerprint
{
    double rmsDb;
    double hDb[5];   // H1..H5 in dBFS
};

double toDb(double lin)
{
    return 20.0 * std::log10(std::max(lin, 1.0e-12));
}

double goertzelBin(const std::vector<double>& x, double freq)
{
    const double w = 2.0 * std::numbers::pi * freq / kGoldenSampleRate;
    const double coeff = 2.0 * std::cos(w);
    double s1 = 0.0, s2 = 0.0;
    for (double v : x)
    {
        const double s = v + coeff * s1 - s2;
        s2 = s1; s1 = s;
    }
    const double re = s1 - s2 * std::cos(w);
    const double im = s2 * std::sin(w);
    return 2.0 * std::sqrt(re * re + im * im) / x.size();
}

TubeAmpChainConfig goldenPreset(int idx)
{
    switch (idx)
    {
        case 0: return chain_presets::V72Preamp();
        case 1: return chain_presets::MarshallMode();
        case 2: return chain_presets::CultureVultureMode();
        case 3: return chain_presets::RNDIMode();
        case 4:
        default: return chain_presets::HiFi300BMode();
    }
}

Fingerprint renderFingerprint(int presetIdx, double amp)
{
    TubeAmpChain chain;
    auto cfg = goldenPreset(presetIdx);
    cfg.variationSeed = 0;               // the fixed golden unit
    chain.setup(cfg, kGoldenSampleRate);

    const int N = static_cast<int>(0.75 * kGoldenSampleRate);
    std::vector<double> tail;
    tail.reserve(static_cast<std::size_t>(N / 2));
    for (int n = 0; n < N; ++n)
    {
        const double x = amp * std::sin(2.0 * std::numbers::pi
                                        * kGoldenFreq * n / kGoldenSampleRate);
        const double y = chain.process(x);
        if (n >= N / 2) tail.push_back(y);
    }

    Fingerprint f {};
    double s = 0.0;
    for (double v : tail) s += v * v;
    f.rmsDb = toDb(std::sqrt(s / tail.size()));
    for (int h = 0; h < 5; ++h)
        f.hDb[h] = toDb(goertzelBin(tail, kGoldenFreq * (h + 1)));
    return f;
}

} // namespace

TEST_CASE("Golden render fingerprints match the checked-in reference",
          "[golden]")
{
    static const char* names[5] =
        { "v72", "console", "cv", "rndi", "hifi" };
    for (int p = 0; p < 5; ++p)
    {
        for (int a = 0; a < 2; ++a)
        {
            const auto f = renderFingerprint(p, kGoldenAmps[a]);
            const auto& ref = golden::kReference[p][a];
            INFO("preset " << names[p] << " amp " << kGoldenAmps[a]
                 << "  rms " << f.rmsDb << " (ref " << ref.rmsDb << ")");
            REQUIRE(std::isfinite(f.rmsDb));
            REQUIRE(std::abs(f.rmsDb - ref.rmsDb) < 0.5);
            for (int h = 0; h < 5; ++h)
            {
                if (ref.hDb[h] < -80.0) continue;   // noise-floor bin
                INFO("preset " << names[p] << " amp " << kGoldenAmps[a]
                     << "  H" << (h + 1) << " " << f.hDb[h]
                     << " (ref " << ref.hDb[h] << ")");
                REQUIRE(std::abs(f.hDb[h] - ref.hDb[h]) < 0.5);
            }
        }
    }
}

// Hidden regeneration case: prints the reference header to stdout.
// Run explicitly:  ./tests/valvra_tests "[golden-regen]"
TEST_CASE("Golden render reference regeneration", "[.][golden-regen]")
{
    std::printf("// Auto-generated by the [golden-regen] test case — do not\n");
    std::printf("// hand-edit.  Regenerate whenever a physics change is\n");
    std::printf("// INTENDED to move the sound, and commit alongside it.\n");
    std::printf("#pragma once\n\nnamespace golden {\n\n");
    std::printf("struct Ref { double rmsDb; double hDb[5]; };\n\n");
    std::printf("inline constexpr Ref kReference[5][2] = {\n");
    for (int p = 0; p < 5; ++p)
    {
        std::printf("    {\n");
        for (int a = 0; a < 2; ++a)
        {
            const auto f = renderFingerprint(p, kGoldenAmps[a]);
            std::printf("        { %.6f, { %.6f, %.6f, %.6f, %.6f, %.6f } },\n",
                        f.rmsDb, f.hDb[0], f.hDb[1], f.hDb[2], f.hDb[3],
                        f.hDb[4]);
        }
        std::printf("    },\n");
    }
    std::printf("};\n\n} // namespace golden\n");
    SUCCEED();
}
